<a href="https://colab.research.google.com/github/AtulAravindDas/FinVAR/blob/main/Datasetcreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Cleaning the EPS dataset(obtained it from Compustat Fundamental Annual page)**

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/ticker_eps.csv')

In [ ]:
df

      datadate  fyear datafmt  tic  epspx
0     12/31/15   2015     STD  ABT   1.73
1     12/31/16   2016     STD  ABT   0.71
2     12/31/17   2017     STD  ABT   0.20
3     12/31/18   2018     STD  ABT   1.32
4     12/31/19   2019     STD  ABT   2.07
...        ...    ...     ...  ...    ...
2279  12/31/20   2020     STD  LYB   4.25
2280  12/31/21   2021     STD  LYB  16.79
2281  12/31/22   2022     STD  LYB  11.86
2282  12/31/23   2023     STD  LYB   6.50
2283  12/31/24   2024     STD  LYB   4.15

[2284 rows x 5 columns]

In [ ]:
df.isnull().sum()

datadate      0
fyear         0
datafmt       0
tic           0
epspx       275
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

datadate    0
fyear       0
datafmt     0
tic         0
epspx       0
dtype: int64

In [ ]:
new_df=df
new_df

      datadate  fyear datafmt  tic  epspx
0     12/31/15   2015     STD  ABT   1.73
1     12/31/16   2016     STD  ABT   0.71
2     12/31/17   2017     STD  ABT   0.20
3     12/31/18   2018     STD  ABT   1.32
4     12/31/19   2019     STD  ABT   2.07
...        ...    ...     ...  ...    ...
2279  12/31/20   2020     STD  LYB   4.25
2280  12/31/21   2021     STD  LYB  16.79
2281  12/31/22   2022     STD  LYB  11.86
2282  12/31/23   2023     STD  LYB   6.50
2283  12/31/24   2024     STD  LYB   4.15

[2009 rows x 5 columns]

In [ ]:
new_df.to_csv('updated_ticker_eps.csv',index=False)

# **Cleaning the Financial Ratios Dataset(obtained using Compustat Financial Ratios)**

In [ ]:
financial_ratios=pd.read_csv('/content/drive/MyDrive/Financial_Ratios.csv')
financial_ratios.head()

,permno,adate,qdate,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER
0,10104,2014-05-31,2014-11-30,2015-01-31,17.454,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL
1,10104,2014-05-31,2014-11-30,2015-02-28,18.258,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL
2,10104,2014-05-31,2014-11-30,2015-03-31,17.979,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL
3,10104,2014-05-31,2015-02-28,2015-04-30,18.251,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL
4,10104,2014-05-31,2015-02-28,2015-05-31,18.197,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL

In [ ]:
financial_ratios.drop(columns=['adate','qdate'],axis=1,inplace=True)

In [ ]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             5
dtype: int64

In [ ]:
null_values_ticker_count = financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER
3840,15408,2015-09-30,NaN,0.043,0.221,0.072,0.023,1.373,2.497,1.755,NaN
3841,15408,2015-10-31,NaN,0.043,0.221,0.072,0.023,1.373,2.497,1.755,NaN
4290,16692,2017-07-31,-127.560,-0.017,0.100,0.086,-0.045,14.689,1.151,2.417,NaN
5940,20057,2021-01-31,32.673,0.023,0.168,0.118,0.020,1.588,4.129,1.084,NaN
6828,22623,2022-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
financial_ratios[financial_ratios['permno']==15408]['TICKER'].unique()

array([nan, 'KHC'], dtype=object)

In [ ]:
# Replace null values in 'TICKER' column for permno 15408 with 'KHC'
financial_ratios.loc[(financial_ratios['permno'] == 15408) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'KHC'

In [ ]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             3
dtype: int64

In [ ]:
null_values_ticker_count = financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER
4290,16692,2017-07-31,-127.560,-0.017,0.100,0.086,-0.045,14.689,1.151,2.417,NaN
5940,20057,2021-01-31,32.673,0.023,0.168,0.118,0.020,1.588,4.129,1.084,NaN
6828,22623,2022-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
financial_ratios[financial_ratios['permno']==16692]
financial_ratios[financial_ratios['permno']==16692]['TICKER'].unique()

array([nan, 'GDI', 'IR'], dtype=object)

In [ ]:
financial_ratios[financial_ratios['permno']==20057]['TICKER'].unique()

array([nan, 'VTRS'], dtype=object)

In [ ]:
financial_ratios[financial_ratios['permno']==22623]['TICKER'].unique()

array([nan, 'CEG'], dtype=object)

In [ ]:
# prompt: Replace all the null values in the ticker column having the permno 15408 with KHC in financial_ratios

# Replace null values in 'TICKER' column for permno 15408 with 'KHC'
financial_ratios.loc[(financial_ratios['permno'] == 22623) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'CEG'
financial_ratios.loc[(financial_ratios['permno'] == 20057) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'VTRS'

In [ ]:
null_values_ticker_count=financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER
4290,16692,2017-07-31,-127.56,-0.017,0.1,0.086,-0.045,14.689,1.151,2.417,NaN

In [ ]:
financial_ratios[financial_ratios['permno']==16692]

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER
4290,16692,2017-07-31,-127.560,-0.017,0.100,0.086,-0.045,14.689,1.151,2.417,NaN
4291,16692,2017-08-31,-25.258,-0.084,0.034,0.057,-0.232,6.418,0.424,2.455,GDI
4292,16692,2017-09-30,-29.591,-0.084,0.034,0.057,-0.232,6.418,0.424,2.455,GDI
4293,16692,2017-10-31,-31.022,-0.084,0.034,0.057,-0.232,6.418,0.424,2.455,GDI
4294,16692,2017-11-30,-46.300,-0.059,0.064,0.074,-0.129,4.807,0.937,2.469,GDI
...,...,...,...,...,...,...,...,...,...,...,...
4375,16692,2024-08-31,45.272,0.117,0.194,0.120,0.080,0.630,8.308,2.243,IR
4376,16692,2024-09-30,48.594,0.117,0.194,0.120,0.080,0.630,8.308,2.243,IR
4377,16692,2024-10-31,47.525,0.117,0.194,0.120,0.080,0.630,8.308,2.243,IR
4378,16692,2024-11-30,50.815,0.117,0.199,0.118,0.080,0.678,7.528,2.269,IR
4379,16692,2024-12-31,44.127,0.117,0.199,0.118,0.080,0.678,7.528,2.269,IR

In [ ]:
financial_ratios.loc[(financial_ratios['permno'] == 16692) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'GDI'

In [ ]:
null_values_ticker_count=financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

Empty DataFrame
Columns: [permno, public_date, pe_exi, npm, opmad, roa, roe, de_ratio, intcov_ratio, curr_ratio, TICKER]
Index: []

In [ ]:
null_value_count=financial_ratios.isnull().sum()
null_value_count

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             0
dtype: int64

In [ ]:
df

      datadate  fyear datafmt  tic  epspx
0     12/31/15   2015     STD  ABT   1.73
1     12/31/16   2016     STD  ABT   0.71
2     12/31/17   2017     STD  ABT   0.20
3     12/31/18   2018     STD  ABT   1.32
4     12/31/19   2019     STD  ABT   2.07
...        ...    ...     ...  ...    ...
2279  12/31/20   2020     STD  LYB   4.25
2280  12/31/21   2021     STD  LYB  16.79
2281  12/31/22   2022     STD  LYB  11.86
2282  12/31/23   2023     STD  LYB   6.50
2283  12/31/24   2024     STD  LYB   4.15

[2009 rows x 5 columns]

In [ ]:
import pandas as pd
financial_ratios['year'] = pd.to_datetime(financial_ratios['public_date']).dt.year

In [ ]:
financial_ratios.head()

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER,year
0,10104,2015-01-31,17.454,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015
1,10104,2015-02-28,18.258,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015
2,10104,2015-03-31,17.979,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015
3,10104,2015-04-30,18.251,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015
4,10104,2015-05-31,18.197,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015

In [ ]:
new_df.head()

   datadate  fyear datafmt  tic  epspx
0  12/31/15   2015     STD  ABT   1.73
1  12/31/16   2016     STD  ABT   0.71
2  12/31/17   2017     STD  ABT   0.20
3  12/31/18   2018     STD  ABT   1.32
4  12/31/19   2019     STD  ABT   2.07

In [ ]:
new_df.columns.tolist()

['datadate', 'fyear', 'datafmt', 'tic', 'epspx']

In [ ]:
new_df = new_df.rename(columns={'tic': 'TICKER'})

In [ ]:
import numpy as np

financial_ratios['epspx'] = np.nan


for index, row in financial_ratios.iterrows():
    ticker = row['TICKER']
    year = row['year']

    matching_rows = new_df[(new_df['TICKER'] == ticker) & (new_df['fyear'] == year)]

    if not matching_rows.empty:
        financial_ratios.loc[index, 'epspx'] = matching_rows['epspx'].iloc[0]

In [ ]:
financial_ratios.head()

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER,year,epspx
0,10104,2015-01-31,17.454,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11
1,10104,2015-02-28,18.258,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11
2,10104,2015-03-31,17.979,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11
3,10104,2015-04-30,18.251,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,2.11
4,10104,2015-05-31,18.197,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,2.11

In [ ]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             0
year               0
epspx           1233
dtype: int64

In [ ]:
null_ticker_list=financial_ratios[financial_ratios['epspx'].isnull()]['TICKER'].unique()

In [ ]:
for ticker in null_ticker_list:
  print(ticker)
  print(financial_ratios[financial_ratios['TICKER']==ticker])

ORCL
     permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
0     10104  2015-01-31  17.454  0.281  0.391  0.199  0.238     0.999
1     10104  2015-02-28  18.258  0.281  0.391  0.199  0.238     0.999
2     10104  2015-03-31  17.979  0.281  0.391  0.199  0.238     0.999
3     10104  2015-04-30  18.251  0.279  0.386  0.190  0.232     1.029
4     10104  2015-05-31  18.197  0.279  0.386  0.190  0.232     1.029
..      ...         ...     ...    ...    ...    ...    ...       ...
115   10104  2024-08-31  38.084  0.198  0.297  0.159  0.821    15.135
116   10104  2024-09-30  45.930  0.198  0.297  0.159  0.821    15.135
117   10104  2024-10-31  43.258  0.204  0.304  0.164  1.118    18.116
118   10104  2024-11-30  47.639  0.204  0.304  0.164  1.118    18.116
119   10104  2024-12-31  42.948  0.204  0.304  0.164  1.118    18.116

     intcov_ratio  curr_ratio TICKER  year  epspx
0          14.982       3.837   ORCL  2015   2.11
1          14.982       3.837   ORCL  2015   2.11
2          14.982       3.837   ORCL  2015   2.11
3          14.180       3.916   ORCL  2015   2.11
4          14.180       3.916   ORCL  2015   2.11
..            ...         ...    ...   ...    ...
115         4.481       0.715   ORCL  2024    NaN
116         4.481       0.715   ORCL  2024    NaN
117         4.698       0.762   ORCL  2024    NaN
118         4.698       0.762   ORCL  2024    NaN
119         4.698       0.762   ORCL  2024    NaN

[120 rows x 13 columns]
FISV
     permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
480   10696  2015-01-31  11.736  0.158  0.242  0.171  0.189     1.709
481   10696  2015-02-28  26.110  0.149  0.241  0.171  0.181     1.834
482   10696  2015-03-31  26.555  0.149  0.241  0.171  0.181     1.834
483   10696  2015-04-30  25.953  0.149  0.241  0.171  0.181     1.834
484   10696  2015-05-31  13.096  0.150  0.248  0.177  0.185     1.789
..      ...         ...     ...    ...    ...    ...    ...       ...
578   10696  2023-03-31  28.908  0.143  0.208  0.083  0.073     1.693
579   10696  2023-04-30  31.233  0.143  0.208  0.083  0.073     1.693
580   10696  2023-05-31  29.602  0.134  0.216  0.091  0.070     1.533
581   10696  2023-06-30  33.285  0.134  0.216  0.091  0.070     1.533
582   10696  2023-07-31  33.301  0.134  0.216  0.091  0.070     1.533

     intcov_ratio  curr_ratio TICKER  year  epspx
480         7.390       1.124   FISV  2015    NaN
481         7.457       1.000   FISV  2015    NaN
482         7.457       1.000   FISV  2015    NaN
483         7.457       1.000   FISV  2015    NaN
484         7.755       1.058   FISV  2015    NaN
..            ...         ...    ...   ...    ...
578         4.941       1.041   FISV  2023    NaN
579         4.941       1.041   FISV  2023    NaN
580         5.000       1.055   FISV  2023    NaN
581         5.000       1.055   FISV  2023    NaN
582         5.000       1.055   FISV  2023    NaN

[103 rows x 13 columns]
FI
     permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
583   10696  2023-08-31  30.577  0.136  0.229  0.094  0.073     1.559
584   10696  2023-09-30  28.453  0.136  0.229  0.094  0.073     1.559
585   10696  2023-10-31  28.652  0.136  0.229  0.094  0.073     1.559
586   10696  2023-11-30  27.382  0.158  0.243  0.098  0.088     1.646
587   10696  2023-12-31  27.849  0.158  0.243  0.098  0.088     1.646
588   10696  2024-01-31  29.742  0.158  0.243  0.098  0.088     1.646
589   10696  2024-02-29  29.974  0.161  0.255  0.089  0.091     2.017
590   10696  2024-03-31  32.092  0.161  0.255  0.089  0.091     2.017
591   10696  2024-04-30  30.657  0.161  0.255  0.089  0.091     2.017
592   10696  2024-05-31  27.993  0.167  0.263  0.098  0.098     1.893
593   10696  2024-06-30  27.858  0.167  0.263  0.098  0.098     1.893
594   10696  2024-07-31  30.574  0.167  0.263  0.098  0.098     1.893
595   10696  2024-08-31  30.260  0.174  0.272  0.096  0.105     2.077
596   10696  2024-09-30  31.135  0.174  0.272  0.096  0.105     2.077
597   10696  2024-10-31  34.298  0.174  0.272  0.096  0.105     2.077
598   10696  2024-11-30  42.574  0.152  0.281  0.095  0.095     2.089
599   10696  2024-12-31  39.580  0.152  0.281  0.095  0.095     2.089

     intcov_ratio  curr_ratio TICKER  year  epspx
583         5.004       1.068     FI  2023    NaN
584         5.004       1.068     FI  2023    NaN
585         5.004       1.068     FI  2023    NaN
586         4.978       1.071     FI  2023    NaN
587         4.978       1.071     FI  2023    NaN
588         4.978       1.071     FI  2024    NaN
589         4.855       1.038     FI  2024    NaN
590         4.855       1.038     FI  2024    NaN
591         4.855       1.038     FI  2024    NaN
592         4.805       1.062     FI  2024    NaN
593         4.805       1.062     FI  2024    NaN
594         4.805       1.062     FI  2024    NaN
595         4.801       1.056     FI  2024    NaN
596         4.801       1.056     FI  2024    NaN
597         4.801       1.056     FI  2024    NaN
598         4.746       1.054     FI  2024    NaN
599         4.746       1.054     FI  2024    NaN
FB
      permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
1920   13407  2015-01-31  71.613  0.247  0.446  0.335  0.174     0.141
1921   13407  2015-02-28  71.791  0.236  0.400  0.214  0.112     0.113
1922   13407  2015-03-31  74.741  0.236  0.400  0.214  0.112     0.113
1923   13407  2015-04-30  71.609  0.236  0.400  0.214  0.112     0.113
1924   13407  2015-05-31  76.883  0.208  0.360  0.242  0.120     0.123
...      ...         ...     ...    ...    ...    ...    ...       ...
2006   13407  2022-03-31  16.148  0.334  0.396  0.336  0.311     0.329
2007   13407  2022-04-30  14.558  0.334  0.396  0.336  0.311     0.329
2008   13407  2022-05-31  14.648  0.312  0.367  0.311  0.282     0.290
2009   13407  2022-06-30  12.197  0.312  0.367  0.311  0.282     0.290
2010   13407  2022-07-31  12.035  0.312  0.367  0.311  0.282     0.290

      intcov_ratio  curr_ratio TICKER  year  epspx
1920        52.161      12.825     FB  2015    NaN
1921       216.609       9.600     FB  2015    NaN
1922       216.609       9.600     FB  2015    NaN
1923       216.609       9.600     FB  2015    NaN
1924       216.609      10.742     FB  2015    NaN
...            ...         ...    ...   ...    ...
2006      2032.740       3.154     FB  2022    NaN
2007      2032.740       3.154     FB  2022    NaN
2008      2032.740       3.765     FB  2022    NaN
2009      2032.740       3.765     FB  2022    NaN
2010      2032.740       3.765     FB  2022    NaN

[91 rows x 13 columns]
GDI
      permno public_date   pe_exi    npm  opmad    roa    roe  de_ratio  \
4290   16692  2017-07-31 -127.560 -0.017  0.100  0.086 -0.045    14.689
4291   16692  2017-08-31  -25.258 -0.084  0.034  0.057 -0.232     6.418
4292   16692  2017-09-30  -29.591 -0.084  0.034  0.057 -0.232     6.418
4293   16692  2017-10-31  -31.022 -0.084  0.034  0.057 -0.232     6.418
4294   16692  2017-11-30  -46.300 -0.059  0.064  0.074 -0.129     4.807
4295   16692  2017-12-31  -48.471 -0.059  0.064  0.074 -0.129     4.807
4296   16692  2018-01-31  -49.400 -0.059  0.064  0.074 -0.129     4.807
4297   16692  2018-02-28  355.667  0.008  0.063  0.073  0.015     2.129
4298   16692  2018-03-31  340.889  0.008  0.063  0.073  0.015     2.129
4299   16692  2018-04-30  351.444  0.008  0.063  0.073  0.015     2.129
4300   16692  2018-05-31  131.480  0.027  0.076  0.083  0.047     2.325
4301   16692  2018-06-30  117.560  0.027  0.076  0.083  0.047     2.325
4302   16692  2018-07-31  114.440  0.027  0.076  0.083  0.047     2.325
4303   16692  2018-08-31   21.344  0.105  0.150  0.124  0.160     2.153
4304   16692  2018-09-30   21.634  0.105  0.150  0.124  0.160     2.153
4305   16692  2018-10-31   20.656  0.105  0.150  0.124  0.160     2.153
4306   16692  2018-11-30   16.283  0.121  0.155  0.127  0.181     1.969
4307   16692  2018-12-31   13.454  0.121  0.155  0.127  0.181     1.969
4308   16692  2019-01-31   16.230  0.121  0.155  0.127  0.181     1.969
4309   16692  2019-02-28   20.814  0.100  0.171  0.141  0.147     1.677
4310   16692  2019-03-31   21.558  0.100  0.171  0.141  0.147     1.677
4311   16692  2019-04-30   26.163  0.100  0.171  0.141  0.147     1.677
4312   16692  2019-05-31   25.735  0.102  0.169  0.138  0.146     1.751
4313   16692  2019-06-30   26.212  0.102  0.169  0.138  0.146     1.751
4314   16692  2019-07-31   24.977  0.102  0.169  0.138  0.146     1.751
4315   16692  2019-08-31   23.129  0.098  0.166  0.137  0.135     1.662
4316   16692  2019-09-30   22.815  0.098  0.166  0.137  0.135     1.662
4317   16692  2019-10-31   25.669  0.098  0.166  0.137  0.135     1.662
4318   16692  2019-11-30   31.073  0.089  0.160  0.130  0.115     1.604
4319   16692  2019-12-31   33.651  0.089  0.160  0.130  0.115     1.604
4320   16692  2020-01-31   32.394  0.089  0.160  0.130  0.115     1.604
4321   16692  2020-02-29   43.145  0.065  0.143  0.116  0.078     1.475
4322   16692  2020-03-31   32.632  0.065  0.143  0.116  0.078     1.475
4323   16692  2020-04-30   38.263  0.065  0.143  0.116  0.078     1.475

      intcov_ratio  curr_ratio TICKER  year  epspx
4290         1.151       2.417    GDI  2017    NaN
4291         0.424       2.455    GDI  2017    NaN
4292         0.424       2.455    GDI  2017    NaN
4293         0.424       2.455    GDI  2017    NaN
4294         0.937       2.469    GDI  2017    NaN
4295         0.937       2.469    GDI  2017    NaN
4296         0.937       2.469    GDI  2018    NaN
4297         1.069       2.605    GDI  2018    NaN
4298         1.069       2.605    GDI  2018    NaN
4299         1.069       2.605    GDI  2018    NaN
4300         1.586       2.529    GDI  2018    NaN
4301         1.586       2.529    GDI  2018    NaN
4302         1.586       2.529    GDI  2018    NaN
4303         3.639       2.529    GDI  2018    NaN
4304         3.639       2.529    GDI  2018    NaN
4305         3.639       2.529    GDI  2018    NaN
4306         4.024       2.501    GDI  2018    NaN
4307         4.024       2.501    GDI  2018    NaN
4308         4.024       2.501    GDI  2019    NaN
4309         4.630       2.232    GDI  2019    NaN
4310         4.630       2.232    GDI  2019    NaN
4311         4.630       2.232    GDI  2019    NaN
4312         4.738       2.355    GDI  2019    NaN
4313         4.738       2.355    GDI  2019    NaN
4314         4.738       2.355    GDI  2019    NaN
4315         4.774       2.343    GDI  2019    NaN
4316         4.774       2.343    GDI  2019    NaN
4317         4.774       2.343    GDI  2019    NaN
4318         4.503       2.370    GDI  2019    NaN
4319         4.503       2.370    GDI  2019    NaN
4320         4.503       2.370    GDI  2020    NaN
4321         3.948       2.687    GDI  2020    NaN
4322         3.948       2.687    GDI  2020    NaN
4323         3.948       2.687    GDI  2020    NaN
GIS
      permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
4380   17144  2015-01-31  21.867  0.085  0.154  0.142  0.189     2.559
4381   17144  2015-02-28  22.413  0.085  0.154  0.142  0.189     2.559
4382   17144  2015-03-31  23.583  0.085  0.154  0.142  0.189     2.559
4383   17144  2015-04-30  23.853  0.082  0.152  0.139  0.184     2.717
4384   17144  2015-05-31  24.203  0.082  0.152  0.139  0.184     2.717
...      ...         ...     ...    ...    ...    ...    ...       ...
4495   17144  2024-08-31  16.773  0.126  0.182  0.133  0.207     2.322
4496   17144  2024-09-30  17.135  0.126  0.182  0.133  0.207     2.322
4497   17144  2024-10-31  16.195  0.121  0.178  0.130  0.205     2.316
4498   17144  2024-11-30  15.776  0.121  0.178  0.130  0.205     2.316
4499   17144  2024-12-31  15.183  0.121  0.178  0.130  0.205     2.316

      intcov_ratio  curr_ratio TICKER  year  epspx
4380         8.745       0.847    GIS  2015   2.83
4381         8.745       0.847    GIS  2015   2.83
4382         8.745       0.847    GIS  2015   2.83
4383         8.468       0.772    GIS  2015   2.83
4384         8.468       0.772    GIS  2015   2.83
...            ...         ...    ...   ...    ...
4495         7.113       0.651    GIS  2024    NaN
4496         7.113       0.651    GIS  2024    NaN
4497         7.243       0.652    GIS  2024    NaN
4498         7.243       0.652    GIS  2024    NaN
4499         7.243       0.652    GIS  2024    NaN

[120 rows x 13 columns]
MHFI
      permno public_date   pe_exi    npm  opmad    roa    roe  de_ratio  \
4500   17478  2015-01-31   28.038  0.178  0.353  0.315  0.667     2.715
4501   17478  2015-02-28  -95.463 -0.058  0.361  0.305 -0.286    11.111
4502   17478  2015-03-31  -95.741 -0.058  0.361  0.305 -0.286    11.111
4503   17478  2015-04-30  -96.574 -0.058  0.361  0.305 -0.286    11.111
4504   17478  2015-05-31 -116.570 -0.045  0.370  0.324 -0.189     4.264
4505   17478  2015-06-30 -112.870 -0.045  0.370  0.324 -0.189     4.264
4506   17478  2015-07-31 -114.330 -0.045  0.370  0.324 -0.189     4.264
4507   17478  2015-08-31 -149.220 -0.032  0.381  0.343 -0.162     5.322
4508   17478  2015-09-30 -133.080 -0.032  0.381  0.343 -0.162     5.322
4509   17478  2015-10-31 -142.520 -0.032  0.381  0.343 -0.162     5.322
4510   17478  2015-11-30 -235.290 -0.019  0.386  0.352 -0.118     8.377
4511   17478  2015-12-31 -240.440 -0.019  0.386  0.352 -0.118     8.377
4512   17478  2016-01-31 -207.370 -0.019  0.386  0.352 -0.118     8.377
4513   17478  2016-02-29   21.316  0.218  0.386  0.296  3.038    36.186
4514   17478  2016-03-31   23.511  0.218  0.386  0.296  3.038    36.186
4515   17478  2016-04-30   25.380  0.218  0.386  0.296  3.038    36.186
4516   17478  2016-05-31   26.558  0.213  0.387  0.324  2.107    13.679
4517   17478  2016-06-30   25.477  0.213  0.387  0.324  2.107    13.679
4518   17478  2016-07-31   29.026  0.213  0.387  0.324  2.107    13.679

      intcov_ratio  curr_ratio TICKER  year  epspx
4500        32.481       1.294   MHFI  2015    NaN
4501        30.915       1.000   MHFI  2015    NaN
4502        30.915       1.000   MHFI  2015    NaN
4503        30.915       1.000   MHFI  2015    NaN
4504        31.131       1.148   MHFI  2015    NaN
4505        31.131       1.148   MHFI  2015    NaN
4506        31.131       1.148   MHFI  2015    NaN
4507        31.238       1.169   MHFI  2015    NaN
4508        31.238       1.169   MHFI  2015    NaN
4509        31.238       1.169   MHFI  2015    NaN
4510        24.938       1.125   MHFI  2015    NaN
4511        24.938       1.125   MHFI  2015    NaN
4512        24.938       1.125   MHFI  2016    NaN
4513        20.127       1.133   MHFI  2016    NaN
4514        20.127       1.133   MHFI  2016    NaN
4515        20.127       1.133   MHFI  2016    NaN
4516        16.548       1.203   MHFI  2016    NaN
4517        16.548       1.203   MHFI  2016    NaN
4518        16.548       1.203   MHFI  2016    NaN
UTX
      permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
4860   17830  2015-01-31  16.830  0.105  0.144  0.114  0.197     1.725
4861   17830  2015-02-28  17.875  0.097  0.145  0.123  0.197     1.877
4862   17830  2015-03-31  17.185  0.097  0.145  0.123  0.197     1.877
4863   17830  2015-04-30  16.679  0.097  0.145  0.123  0.197     1.877
4864   17830  2015-05-31  17.130  0.110  0.149  0.111  0.189     1.822
...      ...         ...     ...    ...    ...    ...    ...       ...
4922   17830  2020-03-31  14.716  0.072  0.124  0.091  0.126     2.283
4923   17830  2020-04-30  10.111  0.072  0.124  0.091  0.126     2.283
4924   17830  2020-05-31  17.205  0.071  0.108  0.055  0.078     2.370
4925   17830  2020-06-30  16.432  0.071  0.108  0.055  0.078     2.370
4926   17830  2020-07-31  15.115  0.071  0.108  0.055  0.078     2.370

      intcov_ratio  curr_ratio TICKER  year  epspx
4860         8.539       1.259    UTX  2015    NaN
4861         9.495       1.300    UTX  2015    NaN
4862         9.495       1.300    UTX  2015    NaN
4863         9.495       1.300    UTX  2015    NaN
4864         8.567       1.226    UTX  2015    NaN
...            ...         ...    ...   ...    ...
4922         5.926       1.084    UTX  2020    NaN
4923         5.926       1.084    UTX  2020    NaN
4924         3.049       1.103    UTX  2020    NaN
4925         3.049       1.103    UTX  2020    NaN
4926         3.049       1.103    UTX  2020    NaN

[67 rows x 13 columns]
WAG
      permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
5820   19502  2015-01-31  34.463  0.027  0.048  0.137  0.095      0.92
5821   19502  2015-02-28  38.822  0.027  0.048  0.137  0.095      0.92
5822   19502  2015-03-31  39.570  0.027  0.048  0.137  0.095      0.92

      intcov_ratio  curr_ratio TICKER  year  epspx
5820        21.569       1.667    WAG  2015    NaN
5821        21.569       1.667    WAG  2015    NaN
5822        21.569       1.667    WAG  2015    NaN
CTAS
      permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
7461   23660  2015-01-31   5.654  0.094  0.148  0.188  0.173     1.033
7462   23660  2015-02-28   5.997  0.094  0.148  0.188  0.173     1.033
7463   23660  2015-03-31   5.864  0.094  0.148  0.188  0.173     1.033
7464   23660  2015-04-30   5.491  0.098  0.153  0.187  0.178     1.063
7465   23660  2015-05-31   5.913  0.098  0.153  0.187  0.178     1.063
...      ...         ...     ...    ...    ...    ...    ...       ...
7576   23660  2024-08-31  53.143  0.164  0.216  0.265  0.343     1.124
7577   23660  2024-09-30  54.358  0.164  0.216  0.265  0.343     1.124
7578   23660  2024-10-31  12.993  0.168  0.220  0.273  0.353     1.175
7579   23660  2024-11-30  14.254  0.168  0.220  0.273  0.353     1.175
7580   23660  2024-12-31  11.534  0.168  0.220  0.273  0.353     1.175

      intcov_ratio  curr_ratio TICKER  year  epspx
7461        10.135       2.857   CTAS  2015   4.15
7462        10.135       2.857   CTAS  2015   4.15
7463        10.135       2.857   CTAS  2015   4.15
7464        10.496       2.846   CTAS  2015   4.15
7465        10.496       2.846   CTAS  2015   4.15
...            ...         ...    ...   ...    ...
7576        20.719       1.742   CTAS  2024    NaN
7577        20.719       1.742   CTAS  2024    NaN
7578        21.080       1.908   CTAS  2024    NaN
7579        21.080       1.908   CTAS  2024    NaN
7580        21.080       1.908   CTAS  2024    NaN

[120 rows x 13 columns]
AA
      permno public_date   pe_exi    npm  opmad    roa    roe  de_ratio  \
8061   24643  2015-01-31  -22.357 -0.096  0.074  0.085 -0.191     1.890
8062   24643  2015-02-28   70.429  0.011  0.094  0.099  0.023     1.837
8063   24643  2015-03-31   61.524  0.011  0.094  0.099  0.023     1.837
8064   24643  2015-04-30   63.905  0.011  0.094  0.099  0.023     1.837
8065   24643  2015-05-31   76.531  0.026  0.110  0.110  0.054     1.836
8066   24643  2015-06-30   68.265  0.026  0.110  0.110  0.054     1.836
8067   24643  2015-07-31   60.429  0.026  0.110  0.110  0.054     1.836
8068   24643  2015-08-31   60.319  0.026  0.117  0.114  0.054     1.819
8069   24643  2015-09-30   61.660  0.026  0.117  0.114  0.054     1.819
8070   24643  2015-10-31   57.000  0.026  0.117  0.114  0.054     1.819
8071   24643  2015-11-30   75.892  0.023  0.108  0.105  0.044     1.810
8072   24643  2015-12-31   80.027  0.023  0.108  0.105  0.044     1.810
8073   24643  2016-01-31   59.108  0.023  0.108  0.105  0.044     1.810
8074   24643  2016-02-29  -28.806 -0.014  0.088  0.089 -0.026     1.859
8075   24643  2016-03-31  -30.903 -0.014  0.088  0.089 -0.026     1.859
8076   24643  2016-04-30  -36.032 -0.014  0.088  0.089 -0.026     1.859
8077   24643  2016-05-31  -64.674 -0.023  0.071  0.077 -0.041     1.790
8078   24643  2016-06-30  -64.674 -0.023  0.071  0.077 -0.041     1.790
8079   24643  2016-07-31  -74.093 -0.023  0.071  0.077 -0.041     1.790
8080   24643  2016-08-31  -68.727 -0.024  0.067  0.073 -0.041     1.782
8081   24643  2016-09-30  -69.136 -0.024  0.067  0.073 -0.041     1.782

In [ ]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             0
year               0
epspx           1233
dtype: int64

In [ ]:
missing_percent = financial_ratios.isnull().mean() * 100
print(missing_percent.sort_values(ascending=False))

curr_ratio      13.720697
intcov_ratio     8.416641
epspx            5.382634
roe              4.788929
pe_exi           0.947309
roa              0.144061
opmad            0.091675
npm              0.091675
de_ratio         0.039289
public_date      0.000000
permno           0.000000
TICKER           0.000000
year             0.000000
dtype: float64

In [ ]:
null_cols = ['curr_ratio', 'intcov_ratio', 'epspx', 'roe', 'pe_exi', 'roa', 'opmad', 'npm', 'de_ratio']
for col in null_cols:
  financial_ratios[col].fillna(financial_ratios[col].median(), inplace=True)

<ipython-input-42-3d3a2e1e3d9a>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  financial_ratios[col].fillna(financial_ratios[col].median(), inplace=True)

## **Adding the revenues of the companies based on Ticker Names and Years and also generating the final dataframe to be used for Analysis**

In [ ]:
revenues_df=pd.read_csv('/content/drive/MyDrive/company_revenues.csv')
revenues_df.head()

,gvkey,datadate,fyear,indfmt,consol,popsrc,datafmt,tic,curcd,revt,costat
0,1078,2015-12-31,2015,INDL,C,D,STD,ABT,USD,20405.0,A
1,1078,2016-12-31,2016,INDL,C,D,STD,ABT,USD,20853.0,A
2,1078,2017-12-31,2017,INDL,C,D,STD,ABT,USD,27390.0,A
3,1078,2018-12-31,2018,INDL,C,D,STD,ABT,USD,30578.0,A
4,1078,2019-12-31,2019,INDL,C,D,STD,ABT,USD,31904.0,A

In [ ]:
revenues_df.rename(columns={'tic':'TICKER','fyear':'year'},inplace=True)

In [ ]:
revenues_df.head()

,gvkey,datadate,year,indfmt,consol,popsrc,datafmt,TICKER,curcd,revt,costat
0,1078,2015-12-31,2015,INDL,C,D,STD,ABT,USD,20405.0,A
1,1078,2016-12-31,2016,INDL,C,D,STD,ABT,USD,20853.0,A
2,1078,2017-12-31,2017,INDL,C,D,STD,ABT,USD,27390.0,A
3,1078,2018-12-31,2018,INDL,C,D,STD,ABT,USD,30578.0,A
4,1078,2019-12-31,2019,INDL,C,D,STD,ABT,USD,31904.0,A

In [ ]:
revenues_df.drop(columns=['datadate','gvkey','indfmt','consol','popsrc','datafmt','curcd','costat'],axis=1,inplace=True)
revenues_df.head()

   year TICKER     revt
0  2015    ABT  20405.0
1  2016    ABT  20853.0
2  2017    ABT  27390.0
3  2018    ABT  30578.0
4  2019    ABT  31904.0

In [ ]:
financial_ratios.head()

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER,year,epspx
0,10104,2015-01-31,17.454,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11
1,10104,2015-02-28,18.258,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11
2,10104,2015-03-31,17.979,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11
3,10104,2015-04-30,18.251,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,2.11
4,10104,2015-05-31,18.197,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,2.11

In [ ]:
financial_ratios=financial_ratios.merge(revenues_df[['TICKER','year','revt']],on=['TICKER','year'],how='left')
financial_ratios.head()

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER,year,epspx,revt
0,10104,2015-01-31,17.454,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11,37047.0
1,10104,2015-02-28,18.258,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11,37047.0
2,10104,2015-03-31,17.979,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,2.11,37047.0
3,10104,2015-04-30,18.251,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,2.11,37047.0
4,10104,2015-05-31,18.197,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,2.11,37047.0

In [ ]:
epspx=financial_ratios['epspx']
epspx

0        2.11
1        2.11
2        2.11
3        2.11
4        2.11
         ...
26303    2.23
26304    2.23
26305    2.23
26306    2.23
26307    2.23
Name: epspx, Length: 26308, dtype: float64

In [ ]:
financial_ratios.drop(columns=['epspx'],axis=1,inplace=True)
financial_ratios['EPS']=epspx
financial_ratios.head()

,permno,public_date,pe_exi,npm,opmad,roa,roe,de_ratio,intcov_ratio,curr_ratio,TICKER,year,revt,EPS
0,10104,2015-01-31,17.454,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,37047.0,2.11
1,10104,2015-02-28,18.258,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,37047.0,2.11
2,10104,2015-03-31,17.979,0.281,0.391,0.199,0.238,0.999,14.982,3.837,ORCL,2015,37047.0,2.11
3,10104,2015-04-30,18.251,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,37047.0,2.11
4,10104,2015-05-31,18.197,0.279,0.386,0.190,0.232,1.029,14.180,3.916,ORCL,2015,37047.0,2.11

In [ ]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi             0
npm                0
opmad              0
roa                0
roe                0
de_ratio           0
intcov_ratio       0
curr_ratio         0
TICKER             0
year               0
revt            1233
EPS                0
dtype: int64

In [ ]:
col='revt'
financial_ratios[col].fillna(financial_ratios[col].median(), inplace=True)
financial_ratios.isnull().sum()

<ipython-input-64-978bdf8a85ce>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  financial_ratios[col].fillna(financial_ratios[col].median(), inplace=True)

permno          0
public_date     0
pe_exi          0
npm             0
opmad           0
roa             0
roe             0
de_ratio        0
intcov_ratio    0
curr_ratio      0
TICKER          0
year            0
revt            0
EPS             0
dtype: int64

In [ ]:
financial_ratios.rename(columns={'revt':'Revenue'},inplace=True)

In [ ]:
financial_ratios.to_csv('Financial_ratios_with_eps_and_revenue.csv')